def deployToEnv(String envName, String image) {
    echo "Deploying ${image} to ${envName}"
}

pipeline {
    agent { label 'docker && k8s' }
    stages {
        stage('Clone repository') {
            steps {
              dir('repo') {
                git url: 'https://github.com/romastelchenko/it-academy.21-jenkins-docker-and-pod.git', branch: 'main'
              }
	    }
        }
        stage('Checking repository'){
            steps {
                sh "ls -l"
            }
        }
        stage('Validate Dockerfile') {
            steps {
                sh """
		echo "Validate Dockerfile"
                """
            }
        }
        stage('Build image') {
            steps {
                sh """
                echo "Build image"
                """
            }
        }
        stage('Run and test image') {
            steps {
                sh """
                echo "Run and test image"
                """
            }
        }

        stage('Push image to the registry') {
            steps {
                sh """
                echo "Push image to the registry"
                """
            }
        }

        stage('Aprove deploy') {
            steps {
		script {
			timeout(time: 30, unit: 'MINUTES') {
				input message: 'Deploy to pre-prod?', ok: 'Deploy'
				submitter: 'admin'	
			}
		}
            }
        }
        stage('Deploy to pre-prod') {
            steps {
		sh '''
		APP_IMAGE="ghcr.io/romastelchenko/get-time-app:12-24-25"
		NAMESPACE="pre-prod"
		export APP_IMAGE="${APP_IMAGE}"
		kubectl create namespace "${NAMESPACE}" 2>/dev/null || true
		envsubst < kubernetes/app.yaml | kubectl apply -n "${NAMESPACE}" -f -

                echo "Deploy to pre-prod"
                '''
            }
        }
        stage('Test pre-prod') {
            steps {
                sh """
                echo "Test pre-prod"
                """
            }
        }

        stage('Deploys fun') {
            steps {
                deployToEnv('pre-prod', "1")
                deployToEnv('prod',     "2")
            }
        }

    }
}
